// computes the sales made to customers living in 
// countries where there are no stores

VAR countriesWithActiveStores = 
CALCULATETABLE(
    SUMMARIZE('Sales', 'store'[CountryRegion]), -- get list of active store from sales table
    ALL('Sales') -- ignore all other external filter context 
)

VAR CountriesWithSales =
SUMMARIZE('Sales', 'customers'[CountryRegion])

VAR CountriesWithNoSales =
EXCEPT(CountriesWithSales, countriesWithActiveStores)

VAR Result = 
CALCULATE(
    [Sales Amount],
    CountriesWithNoSales
)

RETURN
Result